/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type InterestConfigStruct = {
  interestRateBps: PromiseOrValue<BigNumberish>;
  numberOfPeriodsPerYear: PromiseOrValue<BigNumberish>;
};

export type InterestConfigStructOutput = [number, number] & {
  interestRateBps: number;
  numberOfPeriodsPerYear: number;
};

export type LoanOfferStruct = {
  termLength: PromiseOrValue<BigNumberish>;
  interestConfig: InterestConfigStruct;
  loanAmount: PromiseOrValue<BigNumberish>;
  creditor: PromiseOrValue<string>;
  debtor: PromiseOrValue<string>;
  description: PromiseOrValue<string>;
  token: PromiseOrValue<string>;
  impairmentGracePeriod: PromiseOrValue<BigNumberish>;
};

export type LoanOfferStructOutput = [
  BigNumber,
  InterestConfigStructOutput,
  BigNumber,
  string,
  string,
  string,
  string,
  BigNumber
] & {
  termLength: BigNumber;
  interestConfig: InterestConfigStructOutput;
  loanAmount: BigNumber;
  creditor: string;
  debtor: string;
  description: string;
  token: string;
  impairmentGracePeriod: BigNumber;
};

export type InterestComputationStateStruct = {
  accruedInterest: PromiseOrValue<BigNumberish>;
  latestPeriodNumber: PromiseOrValue<BigNumberish>;
};

export type InterestComputationStateStructOutput = [BigNumber, BigNumber] & {
  accruedInterest: BigNumber;
  latestPeriodNumber: BigNumber;
};

export type LoanStruct = {
  claimAmount: PromiseOrValue<BigNumberish>;
  paidAmount: PromiseOrValue<BigNumberish>;
  status: PromiseOrValue<BigNumberish>;
  binding: PromiseOrValue<BigNumberish>;
  payerReceivesClaimOnPayment: PromiseOrValue<boolean>;
  debtor: PromiseOrValue<string>;
  token: PromiseOrValue<string>;
  controller: PromiseOrValue<string>;
  dueBy: PromiseOrValue<BigNumberish>;
  acceptedAt: PromiseOrValue<BigNumberish>;
  interestConfig: InterestConfigStruct;
  interestComputationState: InterestComputationStateStruct;
};

export type LoanStructOutput = [
  BigNumber,
  BigNumber,
  number,
  number,
  boolean,
  string,
  string,
  string,
  BigNumber,
  BigNumber,
  InterestConfigStructOutput,
  InterestComputationStateStructOutput
] & {
  claimAmount: BigNumber;
  paidAmount: BigNumber;
  status: number;
  binding: number;
  payerReceivesClaimOnPayment: boolean;
  debtor: string;
  token: string;
  controller: string;
  dueBy: BigNumber;
  acceptedAt: BigNumber;
  interestConfig: InterestConfigStructOutput;
  interestComputationState: InterestComputationStateStructOutput;
};

export type ClaimMetadataStruct = {
  tokenURI: PromiseOrValue<string>;
  attachmentURI: PromiseOrValue<string>;
};

export type ClaimMetadataStructOutput = [string, string] & {
  tokenURI: string;
  attachmentURI: string;
};

export interface BullaFrendLendInterface extends utils.Interface {
  functions: {
    "_bullaClaim()": FunctionFragment;
    "acceptLoan(uint256)": FunctionFragment;
    "admin()": FunctionFragment;
    "fee()": FunctionFragment;
    "getLoan(uint256)": FunctionFragment;
    "getTotalAmountDue(uint256)": FunctionFragment;
    "impairLoan(uint256)": FunctionFragment;
    "loanOfferCount()": FunctionFragment;
    "loanOfferMetadata(uint256)": FunctionFragment;
    "loanOffers(uint256)": FunctionFragment;
    "offerLoan((uint256,(uint16,uint16),uint128,address,address,string,address,uint256))": FunctionFragment;
    "offerLoanWithMetadata((uint256,(uint16,uint16),uint128,address,address,string,address,uint256),(string,string))": FunctionFragment;
    "payLoan(uint256,uint256)": FunctionFragment;
    "protocolFeeBPS()": FunctionFragment;
    "protocolFeeTokens(uint256)": FunctionFragment;
    "protocolFeesByToken(address)": FunctionFragment;
    "rejectLoanOffer(uint256)": FunctionFragment;
    "setProtocolFee(uint256)": FunctionFragment;
    "withdrawAllFees()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_bullaClaim"
      | "acceptLoan"
      | "admin"
      | "fee"
      | "getLoan"
      | "getTotalAmountDue"
      | "impairLoan"
      | "loanOfferCount"
      | "loanOfferMetadata"
      | "loanOffers"
      | "offerLoan"
      | "offerLoanWithMetadata"
      | "payLoan"
      | "protocolFeeBPS"
      | "protocolFeeTokens"
      | "protocolFeesByToken"
      | "rejectLoanOffer"
      | "setProtocolFee"
      | "withdrawAllFees"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_bullaClaim",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptLoan",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAmountDue",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "impairLoan",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "loanOfferCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "loanOfferMetadata",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "loanOffers",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "offerLoan",
    values: [LoanOfferStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "offerLoanWithMetadata",
    values: [LoanOfferStruct, ClaimMetadataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "payLoan",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeBPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeTokens",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeesByToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectLoanOffer",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllFees",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "_bullaClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "acceptLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAmountDue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "impairLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "loanOfferCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loanOfferMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loanOffers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "offerLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "offerLoanWithMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeBPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeesByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectLoanOffer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllFees",
    data: BytesLike
  ): Result;

  events: {
    "LoanOfferAccepted(uint256,uint256)": EventFragment;
    "LoanOfferRejected(uint256,address)": EventFragment;
    "LoanOffered(uint256,address,tuple)": EventFragment;
    "LoanPayment(uint256,uint256,uint256,uint256)": EventFragment;
    "ProtocolFeeUpdated(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LoanOfferAccepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanOfferRejected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanOffered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanPayment"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProtocolFeeUpdated"): EventFragment;
}

export interface LoanOfferAcceptedEventObject {
  loanId: BigNumber;
  claimId: BigNumber;
}
export type LoanOfferAcceptedEvent = TypedEvent<
  [BigNumber, BigNumber],
  LoanOfferAcceptedEventObject
>;

export type LoanOfferAcceptedEventFilter =
  TypedEventFilter<LoanOfferAcceptedEvent>;

export interface LoanOfferRejectedEventObject {
  loanId: BigNumber;
  rejectedBy: string;
}
export type LoanOfferRejectedEvent = TypedEvent<
  [BigNumber, string],
  LoanOfferRejectedEventObject
>;

export type LoanOfferRejectedEventFilter =
  TypedEventFilter<LoanOfferRejectedEvent>;

export interface LoanOfferedEventObject {
  loanId: BigNumber;
  offeredBy: string;
  loanOffer: LoanOfferStructOutput;
}
export type LoanOfferedEvent = TypedEvent<
  [BigNumber, string, LoanOfferStructOutput],
  LoanOfferedEventObject
>;

export type LoanOfferedEventFilter = TypedEventFilter<LoanOfferedEvent>;

export interface LoanPaymentEventObject {
  claimId: BigNumber;
  interestPayment: BigNumber;
  principalPayment: BigNumber;
  protocolFee: BigNumber;
}
export type LoanPaymentEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber],
  LoanPaymentEventObject
>;

export type LoanPaymentEventFilter = TypedEventFilter<LoanPaymentEvent>;

export interface ProtocolFeeUpdatedEventObject {
  oldFee: BigNumber;
  newFee: BigNumber;
}
export type ProtocolFeeUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  ProtocolFeeUpdatedEventObject
>;

export type ProtocolFeeUpdatedEventFilter =
  TypedEventFilter<ProtocolFeeUpdatedEvent>;

export interface BullaFrendLend extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BullaFrendLendInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _bullaClaim(overrides?: CallOverrides): Promise<[string]>;

    acceptLoan(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    admin(overrides?: CallOverrides): Promise<[string]>;

    fee(overrides?: CallOverrides): Promise<[BigNumber]>;

    getLoan(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[LoanStructOutput]>;

    getTotalAmountDue(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        remainingPrincipal: BigNumber;
        interest: BigNumber;
      }
    >;

    impairLoan(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    loanOfferCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    loanOfferMetadata(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { tokenURI: string; attachmentURI: string }>;

    loanOffers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        InterestConfigStructOutput,
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber
      ] & {
        termLength: BigNumber;
        interestConfig: InterestConfigStructOutput;
        loanAmount: BigNumber;
        creditor: string;
        debtor: string;
        description: string;
        token: string;
        impairmentGracePeriod: BigNumber;
      }
    >;

    offerLoan(
      offer: LoanOfferStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    offerLoanWithMetadata(
      offer: LoanOfferStruct,
      metadata: ClaimMetadataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    payLoan(
      claimId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    protocolFeeBPS(overrides?: CallOverrides): Promise<[BigNumber]>;

    protocolFeeTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    protocolFeesByToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    rejectLoanOffer(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setProtocolFee(
      _protocolFeeBPS: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawAllFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  _bullaClaim(overrides?: CallOverrides): Promise<string>;

  acceptLoan(
    offerId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  admin(overrides?: CallOverrides): Promise<string>;

  fee(overrides?: CallOverrides): Promise<BigNumber>;

  getLoan(
    claimId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<LoanStructOutput>;

  getTotalAmountDue(
    claimId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      remainingPrincipal: BigNumber;
      interest: BigNumber;
    }
  >;

  impairLoan(
    claimId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  loanOfferCount(overrides?: CallOverrides): Promise<BigNumber>;

  loanOfferMetadata(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, string] & { tokenURI: string; attachmentURI: string }>;

  loanOffers(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      InterestConfigStructOutput,
      BigNumber,
      string,
      string,
      string,
      string,
      BigNumber
    ] & {
      termLength: BigNumber;
      interestConfig: InterestConfigStructOutput;
      loanAmount: BigNumber;
      creditor: string;
      debtor: string;
      description: string;
      token: string;
      impairmentGracePeriod: BigNumber;
    }
  >;

  offerLoan(
    offer: LoanOfferStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  offerLoanWithMetadata(
    offer: LoanOfferStruct,
    metadata: ClaimMetadataStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  payLoan(
    claimId: PromiseOrValue<BigNumberish>,
    paymentAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  protocolFeeBPS(overrides?: CallOverrides): Promise<BigNumber>;

  protocolFeeTokens(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  protocolFeesByToken(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  rejectLoanOffer(
    offerId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setProtocolFee(
    _protocolFeeBPS: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawAllFees(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _bullaClaim(overrides?: CallOverrides): Promise<string>;

    acceptLoan(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<string>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    getLoan(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<LoanStructOutput>;

    getTotalAmountDue(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        remainingPrincipal: BigNumber;
        interest: BigNumber;
      }
    >;

    impairLoan(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    loanOfferCount(overrides?: CallOverrides): Promise<BigNumber>;

    loanOfferMetadata(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { tokenURI: string; attachmentURI: string }>;

    loanOffers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        InterestConfigStructOutput,
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber
      ] & {
        termLength: BigNumber;
        interestConfig: InterestConfigStructOutput;
        loanAmount: BigNumber;
        creditor: string;
        debtor: string;
        description: string;
        token: string;
        impairmentGracePeriod: BigNumber;
      }
    >;

    offerLoan(
      offer: LoanOfferStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    offerLoanWithMetadata(
      offer: LoanOfferStruct,
      metadata: ClaimMetadataStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    payLoan(
      claimId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    protocolFeeBPS(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    protocolFeesByToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rejectLoanOffer(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFee(
      _protocolFeeBPS: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawAllFees(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "LoanOfferAccepted(uint256,uint256)"(
      loanId?: PromiseOrValue<BigNumberish> | null,
      claimId?: PromiseOrValue<BigNumberish> | null
    ): LoanOfferAcceptedEventFilter;
    LoanOfferAccepted(
      loanId?: PromiseOrValue<BigNumberish> | null,
      claimId?: PromiseOrValue<BigNumberish> | null
    ): LoanOfferAcceptedEventFilter;

    "LoanOfferRejected(uint256,address)"(
      loanId?: PromiseOrValue<BigNumberish> | null,
      rejectedBy?: PromiseOrValue<string> | null
    ): LoanOfferRejectedEventFilter;
    LoanOfferRejected(
      loanId?: PromiseOrValue<BigNumberish> | null,
      rejectedBy?: PromiseOrValue<string> | null
    ): LoanOfferRejectedEventFilter;

    "LoanOffered(uint256,address,tuple)"(
      loanId?: PromiseOrValue<BigNumberish> | null,
      offeredBy?: PromiseOrValue<string> | null,
      loanOffer?: null
    ): LoanOfferedEventFilter;
    LoanOffered(
      loanId?: PromiseOrValue<BigNumberish> | null,
      offeredBy?: PromiseOrValue<string> | null,
      loanOffer?: null
    ): LoanOfferedEventFilter;

    "LoanPayment(uint256,uint256,uint256,uint256)"(
      claimId?: PromiseOrValue<BigNumberish> | null,
      interestPayment?: null,
      principalPayment?: null,
      protocolFee?: null
    ): LoanPaymentEventFilter;
    LoanPayment(
      claimId?: PromiseOrValue<BigNumberish> | null,
      interestPayment?: null,
      principalPayment?: null,
      protocolFee?: null
    ): LoanPaymentEventFilter;

    "ProtocolFeeUpdated(uint256,uint256)"(
      oldFee?: null,
      newFee?: null
    ): ProtocolFeeUpdatedEventFilter;
    ProtocolFeeUpdated(
      oldFee?: null,
      newFee?: null
    ): ProtocolFeeUpdatedEventFilter;
  };

  estimateGas: {
    _bullaClaim(overrides?: CallOverrides): Promise<BigNumber>;

    acceptLoan(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    getLoan(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTotalAmountDue(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    impairLoan(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    loanOfferCount(overrides?: CallOverrides): Promise<BigNumber>;

    loanOfferMetadata(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    loanOffers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    offerLoan(
      offer: LoanOfferStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    offerLoanWithMetadata(
      offer: LoanOfferStruct,
      metadata: ClaimMetadataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    payLoan(
      claimId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    protocolFeeBPS(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    protocolFeesByToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rejectLoanOffer(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setProtocolFee(
      _protocolFeeBPS: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawAllFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _bullaClaim(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    acceptLoan(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLoan(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalAmountDue(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    impairLoan(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    loanOfferCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    loanOfferMetadata(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    loanOffers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    offerLoan(
      offer: LoanOfferStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    offerLoanWithMetadata(
      offer: LoanOfferStruct,
      metadata: ClaimMetadataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    payLoan(
      claimId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    protocolFeeBPS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeTokens(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    protocolFeesByToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rejectLoanOffer(
      offerId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolFee(
      _protocolFeeBPS: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawAllFees(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
