/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type InterestConfigStruct = {
  interestRateBps: PromiseOrValue<BigNumberish>;
  numberOfPeriodsPerYear: PromiseOrValue<BigNumberish>;
};

export type InterestConfigStructOutput = [number, number] & {
  interestRateBps: number;
  numberOfPeriodsPerYear: number;
};

export type CreateInvoiceParamsStruct = {
  debtor: PromiseOrValue<string>;
  claimAmount: PromiseOrValue<BigNumberish>;
  dueBy: PromiseOrValue<BigNumberish>;
  deliveryDate: PromiseOrValue<BigNumberish>;
  description: PromiseOrValue<string>;
  token: PromiseOrValue<string>;
  binding: PromiseOrValue<BigNumberish>;
  payerReceivesClaimOnPayment: PromiseOrValue<boolean>;
  lateFeeConfig: InterestConfigStruct;
  impairmentGracePeriod: PromiseOrValue<BigNumberish>;
};

export type CreateInvoiceParamsStructOutput = [
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string,
  number,
  boolean,
  InterestConfigStructOutput,
  BigNumber
] & {
  debtor: string;
  claimAmount: BigNumber;
  dueBy: BigNumber;
  deliveryDate: BigNumber;
  description: string;
  token: string;
  binding: number;
  payerReceivesClaimOnPayment: boolean;
  lateFeeConfig: InterestConfigStructOutput;
  impairmentGracePeriod: BigNumber;
};

export type ClaimMetadataStruct = {
  tokenURI: PromiseOrValue<string>;
  attachmentURI: PromiseOrValue<string>;
};

export type ClaimMetadataStructOutput = [string, string] & {
  tokenURI: string;
  attachmentURI: string;
};

export type PurchaseOrderStateStruct = {
  deliveryDate: PromiseOrValue<BigNumberish>;
  isDelivered: PromiseOrValue<boolean>;
};

export type PurchaseOrderStateStructOutput = [BigNumber, boolean] & {
  deliveryDate: BigNumber;
  isDelivered: boolean;
};

export type InterestComputationStateStruct = {
  accruedInterest: PromiseOrValue<BigNumberish>;
  latestPeriodNumber: PromiseOrValue<BigNumberish>;
};

export type InterestComputationStateStructOutput = [BigNumber, BigNumber] & {
  accruedInterest: BigNumber;
  latestPeriodNumber: BigNumber;
};

export type InvoiceStruct = {
  claimAmount: PromiseOrValue<BigNumberish>;
  paidAmount: PromiseOrValue<BigNumberish>;
  status: PromiseOrValue<BigNumberish>;
  binding: PromiseOrValue<BigNumberish>;
  payerReceivesClaimOnPayment: PromiseOrValue<boolean>;
  debtor: PromiseOrValue<string>;
  token: PromiseOrValue<string>;
  dueBy: PromiseOrValue<BigNumberish>;
  purchaseOrder: PurchaseOrderStateStruct;
  lateFeeConfig: InterestConfigStruct;
  interestComputationState: InterestComputationStateStruct;
};

export type InvoiceStructOutput = [
  BigNumber,
  BigNumber,
  number,
  number,
  boolean,
  string,
  string,
  BigNumber,
  PurchaseOrderStateStructOutput,
  InterestConfigStructOutput,
  InterestComputationStateStructOutput
] & {
  claimAmount: BigNumber;
  paidAmount: BigNumber;
  status: number;
  binding: number;
  payerReceivesClaimOnPayment: boolean;
  debtor: string;
  token: string;
  dueBy: BigNumber;
  purchaseOrder: PurchaseOrderStateStructOutput;
  lateFeeConfig: InterestConfigStructOutput;
  interestComputationState: InterestComputationStateStructOutput;
};

export interface BullaInvoiceInterface extends utils.Interface {
  functions: {
    "_bullaClaim()": FunctionFragment;
    "cancelInvoice(uint256,string)": FunctionFragment;
    "createInvoice((address,uint256,uint256,uint256,string,address,uint8,bool,(uint16,uint16),uint256))": FunctionFragment;
    "createInvoiceWithMetadata((address,uint256,uint256,uint256,string,address,uint8,bool,(uint16,uint16),uint256),(string,string))": FunctionFragment;
    "deliverPurchaseOrder(uint256)": FunctionFragment;
    "getInvoice(uint256)": FunctionFragment;
    "impairInvoice(uint256)": FunctionFragment;
    "payInvoice(uint256,uint256)": FunctionFragment;
    "updateBinding(uint256,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_bullaClaim"
      | "cancelInvoice"
      | "createInvoice"
      | "createInvoiceWithMetadata"
      | "deliverPurchaseOrder"
      | "getInvoice"
      | "impairInvoice"
      | "payInvoice"
      | "updateBinding"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_bullaClaim",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelInvoice",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createInvoice",
    values: [CreateInvoiceParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createInvoiceWithMetadata",
    values: [CreateInvoiceParamsStruct, ClaimMetadataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "deliverPurchaseOrder",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvoice",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "impairInvoice",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "payInvoice",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBinding",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "_bullaClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createInvoiceWithMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deliverPurchaseOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getInvoice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "impairInvoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payInvoice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateBinding",
    data: BytesLike
  ): Result;

  events: {
    "InvoiceCreated(uint256,uint256)": EventFragment;
    "InvoicePaid(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "InvoiceCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InvoicePaid"): EventFragment;
}

export interface InvoiceCreatedEventObject {
  claimId: BigNumber;
  dueBy: BigNumber;
}
export type InvoiceCreatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  InvoiceCreatedEventObject
>;

export type InvoiceCreatedEventFilter = TypedEventFilter<InvoiceCreatedEvent>;

export interface InvoicePaidEventObject {
  claimId: BigNumber;
  interestPaid: BigNumber;
}
export type InvoicePaidEvent = TypedEvent<
  [BigNumber, BigNumber],
  InvoicePaidEventObject
>;

export type InvoicePaidEventFilter = TypedEventFilter<InvoicePaidEvent>;

export interface BullaInvoice extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BullaInvoiceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _bullaClaim(overrides?: CallOverrides): Promise<[string]>;

    cancelInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createInvoice(
      params: CreateInvoiceParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createInvoiceWithMetadata(
      params: CreateInvoiceParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deliverPurchaseOrder(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[InvoiceStructOutput]>;

    impairInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    payInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateBinding(
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  _bullaClaim(overrides?: CallOverrides): Promise<string>;

  cancelInvoice(
    claimId: PromiseOrValue<BigNumberish>,
    note: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createInvoice(
    params: CreateInvoiceParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createInvoiceWithMetadata(
    params: CreateInvoiceParamsStruct,
    metadata: ClaimMetadataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deliverPurchaseOrder(
    claimId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getInvoice(
    claimId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<InvoiceStructOutput>;

  impairInvoice(
    claimId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  payInvoice(
    claimId: PromiseOrValue<BigNumberish>,
    paymentAmount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateBinding(
    claimId: PromiseOrValue<BigNumberish>,
    binding: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _bullaClaim(overrides?: CallOverrides): Promise<string>;

    cancelInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    createInvoice(
      params: CreateInvoiceParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createInvoiceWithMetadata(
      params: CreateInvoiceParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deliverPurchaseOrder(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<InvoiceStructOutput>;

    impairInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    payInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateBinding(
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "InvoiceCreated(uint256,uint256)"(
      claimId?: null,
      dueBy?: null
    ): InvoiceCreatedEventFilter;
    InvoiceCreated(claimId?: null, dueBy?: null): InvoiceCreatedEventFilter;

    "InvoicePaid(uint256,uint256)"(
      claimId?: null,
      interestPaid?: null
    ): InvoicePaidEventFilter;
    InvoicePaid(claimId?: null, interestPaid?: null): InvoicePaidEventFilter;
  };

  estimateGas: {
    _bullaClaim(overrides?: CallOverrides): Promise<BigNumber>;

    cancelInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createInvoice(
      params: CreateInvoiceParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createInvoiceWithMetadata(
      params: CreateInvoiceParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deliverPurchaseOrder(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    impairInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    payInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateBinding(
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _bullaClaim(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cancelInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createInvoice(
      params: CreateInvoiceParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createInvoiceWithMetadata(
      params: CreateInvoiceParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deliverPurchaseOrder(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    impairInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    payInvoice(
      claimId: PromiseOrValue<BigNumberish>,
      paymentAmount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateBinding(
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
