/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type ClaimPaymentApprovalParamStruct = {
  claimId: PromiseOrValue<BigNumberish>;
  approvalDeadline: PromiseOrValue<BigNumberish>;
  approvedAmount: PromiseOrValue<BigNumberish>;
};

export type ClaimPaymentApprovalParamStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber
] & {
  claimId: BigNumber;
  approvalDeadline: BigNumber;
  approvedAmount: BigNumber;
};

export type CreateClaimApprovalStruct = {
  isBindingAllowed: PromiseOrValue<boolean>;
  approvalType: PromiseOrValue<BigNumberish>;
  approvalCount: PromiseOrValue<BigNumberish>;
  nonce: PromiseOrValue<BigNumberish>;
};

export type CreateClaimApprovalStructOutput = [
  boolean,
  number,
  BigNumber,
  BigNumber
] & {
  isBindingAllowed: boolean;
  approvalType: number;
  approvalCount: BigNumber;
  nonce: BigNumber;
};

export type ClaimPaymentApprovalStruct = {
  claimId: PromiseOrValue<BigNumberish>;
  approvalDeadline: PromiseOrValue<BigNumberish>;
  approvedAmount: PromiseOrValue<BigNumberish>;
};

export type ClaimPaymentApprovalStructOutput = [
  BigNumber,
  number,
  BigNumber
] & { claimId: BigNumber; approvalDeadline: number; approvedAmount: BigNumber };

export type PayClaimApprovalStruct = {
  approvalType: PromiseOrValue<BigNumberish>;
  approvalDeadline: PromiseOrValue<BigNumberish>;
  nonce: PromiseOrValue<BigNumberish>;
  claimApprovals: ClaimPaymentApprovalStruct[];
};

export type PayClaimApprovalStructOutput = [
  number,
  number,
  BigNumber,
  ClaimPaymentApprovalStructOutput[]
] & {
  approvalType: number;
  approvalDeadline: number;
  nonce: BigNumber;
  claimApprovals: ClaimPaymentApprovalStructOutput[];
};

export type UpdateBindingApprovalStruct = {
  approvalCount: PromiseOrValue<BigNumberish>;
  nonce: PromiseOrValue<BigNumberish>;
};

export type UpdateBindingApprovalStructOutput = [BigNumber, BigNumber] & {
  approvalCount: BigNumber;
  nonce: BigNumber;
};

export type CancelClaimApprovalStruct = {
  approvalCount: PromiseOrValue<BigNumberish>;
  nonce: PromiseOrValue<BigNumberish>;
};

export type CancelClaimApprovalStructOutput = [BigNumber, BigNumber] & {
  approvalCount: BigNumber;
  nonce: BigNumber;
};

export type ImpairClaimApprovalStruct = {
  approvalCount: PromiseOrValue<BigNumberish>;
  nonce: PromiseOrValue<BigNumberish>;
};

export type ImpairClaimApprovalStructOutput = [BigNumber, BigNumber] & {
  approvalCount: BigNumber;
  nonce: BigNumber;
};

export type CreateClaimParamsStruct = {
  creditor: PromiseOrValue<string>;
  debtor: PromiseOrValue<string>;
  claimAmount: PromiseOrValue<BigNumberish>;
  description: PromiseOrValue<string>;
  token: PromiseOrValue<string>;
  binding: PromiseOrValue<BigNumberish>;
  payerReceivesClaimOnPayment: PromiseOrValue<boolean>;
  dueBy: PromiseOrValue<BigNumberish>;
  impairmentGracePeriod: PromiseOrValue<BigNumberish>;
};

export type CreateClaimParamsStructOutput = [
  string,
  string,
  BigNumber,
  string,
  string,
  number,
  boolean,
  BigNumber,
  BigNumber
] & {
  creditor: string;
  debtor: string;
  claimAmount: BigNumber;
  description: string;
  token: string;
  binding: number;
  payerReceivesClaimOnPayment: boolean;
  dueBy: BigNumber;
  impairmentGracePeriod: BigNumber;
};

export type ClaimMetadataStruct = {
  tokenURI: PromiseOrValue<string>;
  attachmentURI: PromiseOrValue<string>;
};

export type ClaimMetadataStructOutput = [string, string] & {
  tokenURI: string;
  attachmentURI: string;
};

export type ClaimStruct = {
  claimAmount: PromiseOrValue<BigNumberish>;
  paidAmount: PromiseOrValue<BigNumberish>;
  status: PromiseOrValue<BigNumberish>;
  binding: PromiseOrValue<BigNumberish>;
  payerReceivesClaimOnPayment: PromiseOrValue<boolean>;
  originalCreditor: PromiseOrValue<string>;
  debtor: PromiseOrValue<string>;
  token: PromiseOrValue<string>;
  controller: PromiseOrValue<string>;
  dueBy: PromiseOrValue<BigNumberish>;
  impairmentGracePeriod: PromiseOrValue<BigNumberish>;
};

export type ClaimStructOutput = [
  BigNumber,
  BigNumber,
  number,
  number,
  boolean,
  string,
  string,
  string,
  string,
  BigNumber,
  BigNumber
] & {
  claimAmount: BigNumber;
  paidAmount: BigNumber;
  status: number;
  binding: number;
  payerReceivesClaimOnPayment: boolean;
  originalCreditor: string;
  debtor: string;
  token: string;
  controller: string;
  dueBy: BigNumber;
  impairmentGracePeriod: BigNumber;
};

export interface BullaClaimInterface extends utils.Interface {
  functions: {
    "DOMAIN_SEPARATOR()": FunctionFragment;
    "approvals(address,address)": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "batch(bytes[],bool)": FunctionFragment;
    "cancelClaim(uint256,string)": FunctionFragment;
    "cancelClaimFrom(address,uint256,string)": FunctionFragment;
    "claimMetadata(uint256)": FunctionFragment;
    "claimMetadataGenerator()": FunctionFragment;
    "createClaim((address,address,uint256,string,address,uint8,bool,uint256,uint256))": FunctionFragment;
    "createClaimFrom(address,(address,address,uint256,string,address,uint8,bool,uint256,uint256))": FunctionFragment;
    "createClaimWithMetadata((address,address,uint256,string,address,uint8,bool,uint256,uint256),(string,string))": FunctionFragment;
    "createClaimWithMetadataFrom(address,(address,address,uint256,string,address,uint8,bool,uint256,uint256),(string,string))": FunctionFragment;
    "currentClaimId()": FunctionFragment;
    "extensionRegistry()": FunctionFragment;
    "getApproved(uint256)": FunctionFragment;
    "getClaim(uint256)": FunctionFragment;
    "impairClaim(uint256)": FunctionFragment;
    "impairClaimFrom(address,uint256)": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "lockState()": FunctionFragment;
    "name()": FunctionFragment;
    "owner()": FunctionFragment;
    "ownerOf(uint256)": FunctionFragment;
    "payClaim(uint256,uint256)": FunctionFragment;
    "payClaimFrom(address,uint256,uint256)": FunctionFragment;
    "payClaimFromControllerWithoutTransfer(address,uint256,uint256)": FunctionFragment;
    "permitCancelClaim(address,address,uint64,bytes)": FunctionFragment;
    "permitCreateClaim(address,address,uint8,uint64,bool,bytes)": FunctionFragment;
    "permitImpairClaim(address,address,uint64,bytes)": FunctionFragment;
    "permitPayClaim(address,address,uint8,uint256,(uint256,uint256,uint256)[],bytes)": FunctionFragment;
    "permitToken(address,address,address,uint256,uint256,uint8,bytes32,bytes32)": FunctionFragment;
    "permitUpdateBinding(address,address,uint64,bytes)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "safeTransferFrom(address,address,uint256)": FunctionFragment;
    "safeTransferFrom(address,address,uint256,bytes)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "setClaimMetadataGenerator(address)": FunctionFragment;
    "setExtensionRegistry(address)": FunctionFragment;
    "setLockState(uint8)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "symbol()": FunctionFragment;
    "tokenURI(uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateBinding(uint256,uint8)": FunctionFragment;
    "updateBindingFrom(address,uint256,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "DOMAIN_SEPARATOR"
      | "approvals"
      | "approve"
      | "balanceOf"
      | "batch"
      | "cancelClaim"
      | "cancelClaimFrom"
      | "claimMetadata"
      | "claimMetadataGenerator"
      | "createClaim"
      | "createClaimFrom"
      | "createClaimWithMetadata"
      | "createClaimWithMetadataFrom"
      | "currentClaimId"
      | "extensionRegistry"
      | "getApproved"
      | "getClaim"
      | "impairClaim"
      | "impairClaimFrom"
      | "isApprovedForAll"
      | "lockState"
      | "name"
      | "owner"
      | "ownerOf"
      | "payClaim"
      | "payClaimFrom"
      | "payClaimFromControllerWithoutTransfer"
      | "permitCancelClaim"
      | "permitCreateClaim"
      | "permitImpairClaim"
      | "permitPayClaim"
      | "permitToken"
      | "permitUpdateBinding"
      | "renounceOwnership"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setClaimMetadataGenerator"
      | "setExtensionRegistry"
      | "setLockState"
      | "supportsInterface"
      | "symbol"
      | "tokenURI"
      | "transferFrom"
      | "transferOwnership"
      | "updateBinding"
      | "updateBindingFrom"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approvals",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "batch",
    values: [PromiseOrValue<BytesLike>[], PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelClaim",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelClaimFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimMetadata",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimMetadataGenerator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createClaim",
    values: [CreateClaimParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createClaimFrom",
    values: [PromiseOrValue<string>, CreateClaimParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createClaimWithMetadata",
    values: [CreateClaimParamsStruct, ClaimMetadataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createClaimWithMetadataFrom",
    values: [
      PromiseOrValue<string>,
      CreateClaimParamsStruct,
      ClaimMetadataStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "currentClaimId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "extensionRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaim",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "impairClaim",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "impairClaimFrom",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "lockState", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "payClaim",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "payClaimFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payClaimFromControllerWithoutTransfer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "permitCancelClaim",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "permitCreateClaim",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "permitImpairClaim",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "permitPayClaim",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      ClaimPaymentApprovalParamStruct[],
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "permitToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "permitUpdateBinding",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimMetadataGenerator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setExtensionRegistry",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setLockState",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBinding",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBindingFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approvals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelClaimFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimMetadataGenerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createClaimFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createClaimWithMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createClaimWithMetadataFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentClaimId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extensionRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "impairClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "impairClaimFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockState", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payClaimFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payClaimFromControllerWithoutTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "permitCancelClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "permitCreateClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "permitImpairClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "permitPayClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "permitToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "permitUpdateBinding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimMetadataGenerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExtensionRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLockState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBinding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBindingFrom",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "BindingUpdated(uint256,address,uint8)": EventFragment;
    "CancelClaimApproved(address,address,uint256)": EventFragment;
    "ClaimCreated(uint256,address,address,address,uint256,string,address,address,uint8)": EventFragment;
    "ClaimImpaired(uint256)": EventFragment;
    "ClaimPayment(uint256,address,uint256,uint256)": EventFragment;
    "ClaimRejected(uint256,address,string)": EventFragment;
    "ClaimRescinded(uint256,address,string)": EventFragment;
    "CreateClaimApproved(address,address,uint8,uint256,bool)": EventFragment;
    "ImpairClaimApproved(address,address,uint256)": EventFragment;
    "MetadataAdded(uint256,string,string)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PayClaimApproved(address,address,uint8,uint256,tuple[])": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
    "UpdateBindingApproved(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BindingUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CancelClaimApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimImpaired"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimPayment"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimRejected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimRescinded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateClaimApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ImpairClaimApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MetadataAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PayClaimApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateBindingApproved"): EventFragment;
}

export interface ApprovalEventObject {
  owner: string;
  spender: string;
  id: BigNumber;
}
export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  ApprovalEventObject
>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface ApprovalForAllEventObject {
  owner: string;
  operator: string;
  approved: boolean;
}
export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  ApprovalForAllEventObject
>;

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>;

export interface BindingUpdatedEventObject {
  claimId: BigNumber;
  from: string;
  binding: number;
}
export type BindingUpdatedEvent = TypedEvent<
  [BigNumber, string, number],
  BindingUpdatedEventObject
>;

export type BindingUpdatedEventFilter = TypedEventFilter<BindingUpdatedEvent>;

export interface CancelClaimApprovedEventObject {
  user: string;
  operator: string;
  approvalCount: BigNumber;
}
export type CancelClaimApprovedEvent = TypedEvent<
  [string, string, BigNumber],
  CancelClaimApprovedEventObject
>;

export type CancelClaimApprovedEventFilter =
  TypedEventFilter<CancelClaimApprovedEvent>;

export interface ClaimCreatedEventObject {
  claimId: BigNumber;
  from: string;
  creditor: string;
  debtor: string;
  claimAmount: BigNumber;
  description: string;
  token: string;
  controller: string;
  binding: number;
}
export type ClaimCreatedEvent = TypedEvent<
  [
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    string,
    string,
    string,
    number
  ],
  ClaimCreatedEventObject
>;

export type ClaimCreatedEventFilter = TypedEventFilter<ClaimCreatedEvent>;

export interface ClaimImpairedEventObject {
  claimId: BigNumber;
}
export type ClaimImpairedEvent = TypedEvent<
  [BigNumber],
  ClaimImpairedEventObject
>;

export type ClaimImpairedEventFilter = TypedEventFilter<ClaimImpairedEvent>;

export interface ClaimPaymentEventObject {
  claimId: BigNumber;
  paidBy: string;
  paymentAmount: BigNumber;
  totalPaidAmount: BigNumber;
}
export type ClaimPaymentEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  ClaimPaymentEventObject
>;

export type ClaimPaymentEventFilter = TypedEventFilter<ClaimPaymentEvent>;

export interface ClaimRejectedEventObject {
  claimId: BigNumber;
  from: string;
  note: string;
}
export type ClaimRejectedEvent = TypedEvent<
  [BigNumber, string, string],
  ClaimRejectedEventObject
>;

export type ClaimRejectedEventFilter = TypedEventFilter<ClaimRejectedEvent>;

export interface ClaimRescindedEventObject {
  claimId: BigNumber;
  from: string;
  note: string;
}
export type ClaimRescindedEvent = TypedEvent<
  [BigNumber, string, string],
  ClaimRescindedEventObject
>;

export type ClaimRescindedEventFilter = TypedEventFilter<ClaimRescindedEvent>;

export interface CreateClaimApprovedEventObject {
  user: string;
  operator: string;
  approvalType: number;
  approvalCount: BigNumber;
  isBindingAllowed: boolean;
}
export type CreateClaimApprovedEvent = TypedEvent<
  [string, string, number, BigNumber, boolean],
  CreateClaimApprovedEventObject
>;

export type CreateClaimApprovedEventFilter =
  TypedEventFilter<CreateClaimApprovedEvent>;

export interface ImpairClaimApprovedEventObject {
  user: string;
  operator: string;
  approvalCount: BigNumber;
}
export type ImpairClaimApprovedEvent = TypedEvent<
  [string, string, BigNumber],
  ImpairClaimApprovedEventObject
>;

export type ImpairClaimApprovedEventFilter =
  TypedEventFilter<ImpairClaimApprovedEvent>;

export interface MetadataAddedEventObject {
  claimId: BigNumber;
  tokenURI: string;
  attachmentURI: string;
}
export type MetadataAddedEvent = TypedEvent<
  [BigNumber, string, string],
  MetadataAddedEventObject
>;

export type MetadataAddedEventFilter = TypedEventFilter<MetadataAddedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PayClaimApprovedEventObject {
  user: string;
  operator: string;
  approvalType: number;
  approvalDeadline: BigNumber;
  paymentApprovals: ClaimPaymentApprovalParamStructOutput[];
}
export type PayClaimApprovedEvent = TypedEvent<
  [string, string, number, BigNumber, ClaimPaymentApprovalParamStructOutput[]],
  PayClaimApprovedEventObject
>;

export type PayClaimApprovedEventFilter =
  TypedEventFilter<PayClaimApprovedEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  id: BigNumber;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface UpdateBindingApprovedEventObject {
  user: string;
  operator: string;
  approvalCount: BigNumber;
}
export type UpdateBindingApprovedEvent = TypedEvent<
  [string, string, BigNumber],
  UpdateBindingApprovedEventObject
>;

export type UpdateBindingApprovedEventFilter =
  TypedEventFilter<UpdateBindingApprovedEvent>;

export interface BullaClaim extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BullaClaimInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<[string]>;

    approvals(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        CreateClaimApprovalStructOutput,
        PayClaimApprovalStructOutput,
        UpdateBindingApprovalStructOutput,
        CancelClaimApprovalStructOutput,
        ImpairClaimApprovalStructOutput
      ] & {
        createClaim: CreateClaimApprovalStructOutput;
        payClaim: PayClaimApprovalStructOutput;
        updateBinding: UpdateBindingApprovalStructOutput;
        cancelClaim: CancelClaimApprovalStructOutput;
        impairClaim: ImpairClaimApprovalStructOutput;
      }
    >;

    approve(
      spender: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    batch(
      calls: PromiseOrValue<BytesLike>[],
      revertOnFail: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelClaim(
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimMetadata(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { tokenURI: string; attachmentURI: string }>;

    claimMetadataGenerator(overrides?: CallOverrides): Promise<[string]>;

    createClaim(
      params: CreateClaimParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createClaimFrom(
      from: PromiseOrValue<string>,
      params: CreateClaimParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createClaimWithMetadata(
      params: CreateClaimParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createClaimWithMetadataFrom(
      from: PromiseOrValue<string>,
      params: CreateClaimParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentClaimId(overrides?: CallOverrides): Promise<[BigNumber]>;

    extensionRegistry(overrides?: CallOverrides): Promise<[string]>;

    getApproved(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getClaim(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ClaimStructOutput] & { claim: ClaimStructOutput }>;

    impairClaim(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    impairClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isApprovedForAll(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    lockState(overrides?: CallOverrides): Promise<[number]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    ownerOf(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { owner: string }>;

    payClaim(
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    payClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    payClaimFromControllerWithoutTransfer(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    permitCancelClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    permitCreateClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    permitImpairClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    permitPayClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    permitToken(
      token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    permitUpdateBinding(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setClaimMetadataGenerator(
      _metadataGenerator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setExtensionRegistry(
      _extensionRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLockState(
      _lockState: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    tokenURI(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateBinding(
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateBindingFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

  approvals(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [
      CreateClaimApprovalStructOutput,
      PayClaimApprovalStructOutput,
      UpdateBindingApprovalStructOutput,
      CancelClaimApprovalStructOutput,
      ImpairClaimApprovalStructOutput
    ] & {
      createClaim: CreateClaimApprovalStructOutput;
      payClaim: PayClaimApprovalStructOutput;
      updateBinding: UpdateBindingApprovalStructOutput;
      cancelClaim: CancelClaimApprovalStructOutput;
      impairClaim: ImpairClaimApprovalStructOutput;
    }
  >;

  approve(
    spender: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  balanceOf(
    owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  batch(
    calls: PromiseOrValue<BytesLike>[],
    revertOnFail: PromiseOrValue<boolean>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelClaim(
    claimId: PromiseOrValue<BigNumberish>,
    note: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelClaimFrom(
    from: PromiseOrValue<string>,
    claimId: PromiseOrValue<BigNumberish>,
    note: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimMetadata(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, string] & { tokenURI: string; attachmentURI: string }>;

  claimMetadataGenerator(overrides?: CallOverrides): Promise<string>;

  createClaim(
    params: CreateClaimParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createClaimFrom(
    from: PromiseOrValue<string>,
    params: CreateClaimParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createClaimWithMetadata(
    params: CreateClaimParamsStruct,
    metadata: ClaimMetadataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createClaimWithMetadataFrom(
    from: PromiseOrValue<string>,
    params: CreateClaimParamsStruct,
    metadata: ClaimMetadataStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentClaimId(overrides?: CallOverrides): Promise<BigNumber>;

  extensionRegistry(overrides?: CallOverrides): Promise<string>;

  getApproved(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getClaim(
    claimId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ClaimStructOutput>;

  impairClaim(
    claimId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  impairClaimFrom(
    from: PromiseOrValue<string>,
    claimId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isApprovedForAll(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  lockState(overrides?: CallOverrides): Promise<number>;

  name(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  ownerOf(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  payClaim(
    claimId: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  payClaimFrom(
    from: PromiseOrValue<string>,
    claimId: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  payClaimFromControllerWithoutTransfer(
    from: PromiseOrValue<string>,
    claimId: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  permitCancelClaim(
    user: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalCount: PromiseOrValue<BigNumberish>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  permitCreateClaim(
    user: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalType: PromiseOrValue<BigNumberish>,
    approvalCount: PromiseOrValue<BigNumberish>,
    isBindingAllowed: PromiseOrValue<boolean>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  permitImpairClaim(
    user: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalCount: PromiseOrValue<BigNumberish>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  permitPayClaim(
    user: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalType: PromiseOrValue<BigNumberish>,
    approvalDeadline: PromiseOrValue<BigNumberish>,
    paymentApprovals: ClaimPaymentApprovalParamStruct[],
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  permitToken(
    token: PromiseOrValue<string>,
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    deadline: PromiseOrValue<BigNumberish>,
    v: PromiseOrValue<BigNumberish>,
    r: PromiseOrValue<BytesLike>,
    s: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  permitUpdateBinding(
    user: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalCount: PromiseOrValue<BigNumberish>,
    signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256)"(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256,bytes)"(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    operator: PromiseOrValue<string>,
    approved: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setClaimMetadataGenerator(
    _metadataGenerator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setExtensionRegistry(
    _extensionRegistry: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLockState(
    _lockState: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  symbol(overrides?: CallOverrides): Promise<string>;

  tokenURI(
    claimId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  transferFrom(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateBinding(
    claimId: PromiseOrValue<BigNumberish>,
    binding: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateBindingFrom(
    from: PromiseOrValue<string>,
    claimId: PromiseOrValue<BigNumberish>,
    binding: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

    approvals(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        CreateClaimApprovalStructOutput,
        PayClaimApprovalStructOutput,
        UpdateBindingApprovalStructOutput,
        CancelClaimApprovalStructOutput,
        ImpairClaimApprovalStructOutput
      ] & {
        createClaim: CreateClaimApprovalStructOutput;
        payClaim: PayClaimApprovalStructOutput;
        updateBinding: UpdateBindingApprovalStructOutput;
        cancelClaim: CancelClaimApprovalStructOutput;
        impairClaim: ImpairClaimApprovalStructOutput;
      }
    >;

    approve(
      spender: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batch(
      calls: PromiseOrValue<BytesLike>[],
      revertOnFail: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelClaim(
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimMetadata(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { tokenURI: string; attachmentURI: string }>;

    claimMetadataGenerator(overrides?: CallOverrides): Promise<string>;

    createClaim(
      params: CreateClaimParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createClaimFrom(
      from: PromiseOrValue<string>,
      params: CreateClaimParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createClaimWithMetadata(
      params: CreateClaimParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createClaimWithMetadataFrom(
      from: PromiseOrValue<string>,
      params: CreateClaimParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    currentClaimId(overrides?: CallOverrides): Promise<BigNumber>;

    extensionRegistry(overrides?: CallOverrides): Promise<string>;

    getApproved(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getClaim(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ClaimStructOutput>;

    impairClaim(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    impairClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    isApprovedForAll(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    lockState(overrides?: CallOverrides): Promise<number>;

    name(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    ownerOf(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    payClaim(
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    payClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    payClaimFromControllerWithoutTransfer(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    permitCancelClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    permitCreateClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    permitImpairClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    permitPayClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    permitToken(
      token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    permitUpdateBinding(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "safeTransferFrom(address,address,uint256)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setClaimMetadataGenerator(
      _metadataGenerator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setExtensionRegistry(
      _extensionRegistry: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setLockState(
      _lockState: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    symbol(overrides?: CallOverrides): Promise<string>;

    tokenURI(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateBinding(
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateBindingFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Approval(address,address,uint256)"(
      owner?: PromiseOrValue<string> | null,
      spender?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null
    ): ApprovalEventFilter;
    Approval(
      owner?: PromiseOrValue<string> | null,
      spender?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null
    ): ApprovalEventFilter;

    "ApprovalForAll(address,address,bool)"(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;
    ApprovalForAll(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;

    "BindingUpdated(uint256,address,uint8)"(
      claimId?: PromiseOrValue<BigNumberish> | null,
      from?: PromiseOrValue<string> | null,
      binding?: PromiseOrValue<BigNumberish> | null
    ): BindingUpdatedEventFilter;
    BindingUpdated(
      claimId?: PromiseOrValue<BigNumberish> | null,
      from?: PromiseOrValue<string> | null,
      binding?: PromiseOrValue<BigNumberish> | null
    ): BindingUpdatedEventFilter;

    "CancelClaimApproved(address,address,uint256)"(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): CancelClaimApprovedEventFilter;
    CancelClaimApproved(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): CancelClaimApprovedEventFilter;

    "ClaimCreated(uint256,address,address,address,uint256,string,address,address,uint8)"(
      claimId?: PromiseOrValue<BigNumberish> | null,
      from?: null,
      creditor?: PromiseOrValue<string> | null,
      debtor?: PromiseOrValue<string> | null,
      claimAmount?: null,
      description?: null,
      token?: null,
      controller?: null,
      binding?: null
    ): ClaimCreatedEventFilter;
    ClaimCreated(
      claimId?: PromiseOrValue<BigNumberish> | null,
      from?: null,
      creditor?: PromiseOrValue<string> | null,
      debtor?: PromiseOrValue<string> | null,
      claimAmount?: null,
      description?: null,
      token?: null,
      controller?: null,
      binding?: null
    ): ClaimCreatedEventFilter;

    "ClaimImpaired(uint256)"(
      claimId?: PromiseOrValue<BigNumberish> | null
    ): ClaimImpairedEventFilter;
    ClaimImpaired(
      claimId?: PromiseOrValue<BigNumberish> | null
    ): ClaimImpairedEventFilter;

    "ClaimPayment(uint256,address,uint256,uint256)"(
      claimId?: PromiseOrValue<BigNumberish> | null,
      paidBy?: PromiseOrValue<string> | null,
      paymentAmount?: null,
      totalPaidAmount?: null
    ): ClaimPaymentEventFilter;
    ClaimPayment(
      claimId?: PromiseOrValue<BigNumberish> | null,
      paidBy?: PromiseOrValue<string> | null,
      paymentAmount?: null,
      totalPaidAmount?: null
    ): ClaimPaymentEventFilter;

    "ClaimRejected(uint256,address,string)"(
      claimId?: PromiseOrValue<BigNumberish> | null,
      from?: PromiseOrValue<string> | null,
      note?: null
    ): ClaimRejectedEventFilter;
    ClaimRejected(
      claimId?: PromiseOrValue<BigNumberish> | null,
      from?: PromiseOrValue<string> | null,
      note?: null
    ): ClaimRejectedEventFilter;

    "ClaimRescinded(uint256,address,string)"(
      claimId?: PromiseOrValue<BigNumberish> | null,
      from?: PromiseOrValue<string> | null,
      note?: null
    ): ClaimRescindedEventFilter;
    ClaimRescinded(
      claimId?: PromiseOrValue<BigNumberish> | null,
      from?: PromiseOrValue<string> | null,
      note?: null
    ): ClaimRescindedEventFilter;

    "CreateClaimApproved(address,address,uint8,uint256,bool)"(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalType?: PromiseOrValue<BigNumberish> | null,
      approvalCount?: null,
      isBindingAllowed?: null
    ): CreateClaimApprovedEventFilter;
    CreateClaimApproved(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalType?: PromiseOrValue<BigNumberish> | null,
      approvalCount?: null,
      isBindingAllowed?: null
    ): CreateClaimApprovedEventFilter;

    "ImpairClaimApproved(address,address,uint256)"(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): ImpairClaimApprovedEventFilter;
    ImpairClaimApproved(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): ImpairClaimApprovedEventFilter;

    "MetadataAdded(uint256,string,string)"(
      claimId?: PromiseOrValue<BigNumberish> | null,
      tokenURI?: null,
      attachmentURI?: null
    ): MetadataAddedEventFilter;
    MetadataAdded(
      claimId?: PromiseOrValue<BigNumberish> | null,
      tokenURI?: null,
      attachmentURI?: null
    ): MetadataAddedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "PayClaimApproved(address,address,uint8,uint256,tuple[])"(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalType?: PromiseOrValue<BigNumberish> | null,
      approvalDeadline?: null,
      paymentApprovals?: null
    ): PayClaimApprovedEventFilter;
    PayClaimApproved(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalType?: PromiseOrValue<BigNumberish> | null,
      approvalDeadline?: null,
      paymentApprovals?: null
    ): PayClaimApprovedEventFilter;

    "Transfer(address,address,uint256)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter;
    Transfer(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter;

    "UpdateBindingApproved(address,address,uint256)"(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): UpdateBindingApprovedEventFilter;
    UpdateBindingApproved(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): UpdateBindingApprovedEventFilter;
  };

  estimateGas: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<BigNumber>;

    approvals(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approve(
      spender: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batch(
      calls: PromiseOrValue<BytesLike>[],
      revertOnFail: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelClaim(
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimMetadata(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimMetadataGenerator(overrides?: CallOverrides): Promise<BigNumber>;

    createClaim(
      params: CreateClaimParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createClaimFrom(
      from: PromiseOrValue<string>,
      params: CreateClaimParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createClaimWithMetadata(
      params: CreateClaimParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createClaimWithMetadataFrom(
      from: PromiseOrValue<string>,
      params: CreateClaimParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentClaimId(overrides?: CallOverrides): Promise<BigNumber>;

    extensionRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    getApproved(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getClaim(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    impairClaim(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    impairClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isApprovedForAll(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lockState(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    ownerOf(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    payClaim(
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    payClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    payClaimFromControllerWithoutTransfer(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    permitCancelClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    permitCreateClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    permitImpairClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    permitPayClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    permitToken(
      token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    permitUpdateBinding(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setClaimMetadataGenerator(
      _metadataGenerator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setExtensionRegistry(
      _extensionRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLockState(
      _lockState: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    tokenURI(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateBinding(
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateBindingFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    approvals(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      spender: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batch(
      calls: PromiseOrValue<BytesLike>[],
      revertOnFail: PromiseOrValue<boolean>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelClaim(
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      note: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimMetadata(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimMetadataGenerator(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createClaim(
      params: CreateClaimParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createClaimFrom(
      from: PromiseOrValue<string>,
      params: CreateClaimParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createClaimWithMetadata(
      params: CreateClaimParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createClaimWithMetadataFrom(
      from: PromiseOrValue<string>,
      params: CreateClaimParamsStruct,
      metadata: ClaimMetadataStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentClaimId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    extensionRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getApproved(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getClaim(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    impairClaim(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    impairClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lockState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerOf(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    payClaim(
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    payClaimFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    payClaimFromControllerWithoutTransfer(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    permitCancelClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    permitCreateClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    permitImpairClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    permitPayClaim(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    permitToken(
      token: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      deadline: PromiseOrValue<BigNumberish>,
      v: PromiseOrValue<BigNumberish>,
      r: PromiseOrValue<BytesLike>,
      s: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    permitUpdateBinding(
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setClaimMetadataGenerator(
      _metadataGenerator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setExtensionRegistry(
      _extensionRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLockState(
      _lockState: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenURI(
      claimId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateBinding(
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateBindingFrom(
      from: PromiseOrValue<string>,
      claimId: PromiseOrValue<BigNumberish>,
      binding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
