/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type ClaimPaymentApprovalParamStruct = {
  claimId: PromiseOrValue<BigNumberish>;
  approvalDeadline: PromiseOrValue<BigNumberish>;
  approvedAmount: PromiseOrValue<BigNumberish>;
};

export type ClaimPaymentApprovalParamStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber
] & {
  claimId: BigNumber;
  approvalDeadline: BigNumber;
  approvedAmount: BigNumber;
};

export interface BullaClaimPermitLibInterface extends utils.Interface {
  functions: {
    "getPermitCancelClaimDigest(BullaExtensionRegistry,address,address,uint64,uint64)": FunctionFragment;
    "getPermitCancelClaimMessage(BullaExtensionRegistry,address,uint64)": FunctionFragment;
    "getPermitCreateClaimDigest(BullaExtensionRegistry,address,address,uint8,uint64,bool,uint64)": FunctionFragment;
    "getPermitCreateClaimMessage(BullaExtensionRegistry,address,uint8,uint64,bool)": FunctionFragment;
    "getPermitImpairClaimDigest(BullaExtensionRegistry,address,address,uint64,uint64)": FunctionFragment;
    "getPermitImpairClaimMessage(BullaExtensionRegistry,address,uint64)": FunctionFragment;
    "getPermitPayClaimDigest(BullaExtensionRegistry,address,address,uint8,uint256,(uint256,uint256,uint256)[],uint256)": FunctionFragment;
    "getPermitPayClaimMessage(BullaExtensionRegistry,address,uint8,uint256)": FunctionFragment;
    "getPermitUpdateBindingDigest(BullaExtensionRegistry,address,address,uint64,uint64)": FunctionFragment;
    "getPermitUpdateBindingMessage(BullaExtensionRegistry,address,uint64)": FunctionFragment;
    "hashPaymentApprovals((uint256,uint256,uint256)[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getPermitCancelClaimDigest"
      | "getPermitCancelClaimMessage"
      | "getPermitCreateClaimDigest"
      | "getPermitCreateClaimMessage"
      | "getPermitImpairClaimDigest"
      | "getPermitImpairClaimMessage"
      | "getPermitPayClaimDigest"
      | "getPermitPayClaimMessage"
      | "getPermitUpdateBindingDigest"
      | "getPermitUpdateBindingMessage"
      | "hashPaymentApprovals"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPermitCancelClaimDigest",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermitCancelClaimMessage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermitCreateClaimDigest",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermitCreateClaimMessage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermitImpairClaimDigest",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermitImpairClaimMessage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermitPayClaimDigest",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      ClaimPaymentApprovalParamStruct[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermitPayClaimMessage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermitUpdateBindingDigest",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPermitUpdateBindingMessage",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hashPaymentApprovals",
    values: [ClaimPaymentApprovalParamStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPermitCancelClaimDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermitCancelClaimMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermitCreateClaimDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermitCreateClaimMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermitImpairClaimDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermitImpairClaimMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermitPayClaimDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermitPayClaimMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermitUpdateBindingDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPermitUpdateBindingMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashPaymentApprovals",
    data: BytesLike
  ): Result;

  events: {
    "CancelClaimApproved(address,address,uint256)": EventFragment;
    "CreateClaimApproved(address,address,uint8,uint256,bool)": EventFragment;
    "ImpairClaimApproved(address,address,uint256)": EventFragment;
    "PayClaimApproved(address,address,uint8,uint256,tuple[])": EventFragment;
    "UpdateBindingApproved(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CancelClaimApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateClaimApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ImpairClaimApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PayClaimApproved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateBindingApproved"): EventFragment;
}

export interface CancelClaimApprovedEventObject {
  user: string;
  operator: string;
  approvalCount: BigNumber;
}
export type CancelClaimApprovedEvent = TypedEvent<
  [string, string, BigNumber],
  CancelClaimApprovedEventObject
>;

export type CancelClaimApprovedEventFilter =
  TypedEventFilter<CancelClaimApprovedEvent>;

export interface CreateClaimApprovedEventObject {
  user: string;
  operator: string;
  approvalType: number;
  approvalCount: BigNumber;
  isBindingAllowed: boolean;
}
export type CreateClaimApprovedEvent = TypedEvent<
  [string, string, number, BigNumber, boolean],
  CreateClaimApprovedEventObject
>;

export type CreateClaimApprovedEventFilter =
  TypedEventFilter<CreateClaimApprovedEvent>;

export interface ImpairClaimApprovedEventObject {
  user: string;
  operator: string;
  approvalCount: BigNumber;
}
export type ImpairClaimApprovedEvent = TypedEvent<
  [string, string, BigNumber],
  ImpairClaimApprovedEventObject
>;

export type ImpairClaimApprovedEventFilter =
  TypedEventFilter<ImpairClaimApprovedEvent>;

export interface PayClaimApprovedEventObject {
  user: string;
  operator: string;
  approvalType: number;
  approvalDeadline: BigNumber;
  paymentApprovals: ClaimPaymentApprovalParamStructOutput[];
}
export type PayClaimApprovedEvent = TypedEvent<
  [string, string, number, BigNumber, ClaimPaymentApprovalParamStructOutput[]],
  PayClaimApprovedEventObject
>;

export type PayClaimApprovedEventFilter =
  TypedEventFilter<PayClaimApprovedEvent>;

export interface UpdateBindingApprovedEventObject {
  user: string;
  operator: string;
  approvalCount: BigNumber;
}
export type UpdateBindingApprovedEvent = TypedEvent<
  [string, string, BigNumber],
  UpdateBindingApprovedEventObject
>;

export type UpdateBindingApprovedEventFilter =
  TypedEventFilter<UpdateBindingApprovedEvent>;

export interface BullaClaimPermitLib extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BullaClaimPermitLibInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getPermitCancelClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPermitCancelClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPermitCreateClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPermitCreateClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPermitImpairClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPermitImpairClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPermitPayClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPermitPayClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPermitUpdateBindingDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPermitUpdateBindingMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    hashPaymentApprovals(
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  getPermitCancelClaimDigest(
    extensionRegistry: PromiseOrValue<string>,
    user: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalCount: PromiseOrValue<BigNumberish>,
    nonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getPermitCancelClaimMessage(
    extensionRegistry: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalCount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getPermitCreateClaimDigest(
    extensionRegistry: PromiseOrValue<string>,
    user: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalType: PromiseOrValue<BigNumberish>,
    approvalCount: PromiseOrValue<BigNumberish>,
    isBindingAllowed: PromiseOrValue<boolean>,
    nonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getPermitCreateClaimMessage(
    extensionRegistry: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalType: PromiseOrValue<BigNumberish>,
    approvalCount: PromiseOrValue<BigNumberish>,
    isBindingAllowed: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<string>;

  getPermitImpairClaimDigest(
    extensionRegistry: PromiseOrValue<string>,
    user: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalCount: PromiseOrValue<BigNumberish>,
    nonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getPermitImpairClaimMessage(
    extensionRegistry: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalCount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getPermitPayClaimDigest(
    extensionRegistry: PromiseOrValue<string>,
    user: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalType: PromiseOrValue<BigNumberish>,
    approvalDeadline: PromiseOrValue<BigNumberish>,
    paymentApprovals: ClaimPaymentApprovalParamStruct[],
    nonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getPermitPayClaimMessage(
    extensionRegistry: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalType: PromiseOrValue<BigNumberish>,
    approvalDeadline: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getPermitUpdateBindingDigest(
    extensionRegistry: PromiseOrValue<string>,
    user: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalCount: PromiseOrValue<BigNumberish>,
    nonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getPermitUpdateBindingMessage(
    extensionRegistry: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    approvalCount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  hashPaymentApprovals(
    paymentApprovals: ClaimPaymentApprovalParamStruct[],
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getPermitCancelClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getPermitCancelClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getPermitCreateClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getPermitCreateClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<string>;

    getPermitImpairClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getPermitImpairClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getPermitPayClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getPermitPayClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getPermitUpdateBindingDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getPermitUpdateBindingMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    hashPaymentApprovals(
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "CancelClaimApproved(address,address,uint256)"(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): CancelClaimApprovedEventFilter;
    CancelClaimApproved(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): CancelClaimApprovedEventFilter;

    "CreateClaimApproved(address,address,uint8,uint256,bool)"(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalType?: PromiseOrValue<BigNumberish> | null,
      approvalCount?: null,
      isBindingAllowed?: null
    ): CreateClaimApprovedEventFilter;
    CreateClaimApproved(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalType?: PromiseOrValue<BigNumberish> | null,
      approvalCount?: null,
      isBindingAllowed?: null
    ): CreateClaimApprovedEventFilter;

    "ImpairClaimApproved(address,address,uint256)"(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): ImpairClaimApprovedEventFilter;
    ImpairClaimApproved(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): ImpairClaimApprovedEventFilter;

    "PayClaimApproved(address,address,uint8,uint256,tuple[])"(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalType?: PromiseOrValue<BigNumberish> | null,
      approvalDeadline?: null,
      paymentApprovals?: null
    ): PayClaimApprovedEventFilter;
    PayClaimApproved(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalType?: PromiseOrValue<BigNumberish> | null,
      approvalDeadline?: null,
      paymentApprovals?: null
    ): PayClaimApprovedEventFilter;

    "UpdateBindingApproved(address,address,uint256)"(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): UpdateBindingApprovedEventFilter;
    UpdateBindingApproved(
      user?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approvalCount?: null
    ): UpdateBindingApprovedEventFilter;
  };

  estimateGas: {
    getPermitCancelClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPermitCancelClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPermitCreateClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPermitCreateClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPermitImpairClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPermitImpairClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPermitPayClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPermitPayClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPermitUpdateBindingDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPermitUpdateBindingMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashPaymentApprovals(
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPermitCancelClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPermitCancelClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPermitCreateClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPermitCreateClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalCount: PromiseOrValue<BigNumberish>,
      isBindingAllowed: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPermitImpairClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPermitImpairClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPermitPayClaimDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPermitPayClaimMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalType: PromiseOrValue<BigNumberish>,
      approvalDeadline: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPermitUpdateBindingDigest(
      extensionRegistry: PromiseOrValue<string>,
      user: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPermitUpdateBindingMessage(
      extensionRegistry: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      approvalCount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashPaymentApprovals(
      paymentApprovals: ClaimPaymentApprovalParamStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
